services:
  # magento:
  #   image: php:7.4-fpm
  #   build:
  #     context: ./php
  #   container_name: magento_app
  #   working_dir: /var/www/html
  #   volumes:
  #     - ./src:/var/www/html/
  #   depends_on:
  #     - db
  #     - redis
  #     - elasticsearch
  #   networks:
  #     - net-magento

  # nginx:
  #   image: nginx:1.18
  #   container_name: magento_nginx
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./src:/var/www/html
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - magento
  #   networks:
  #     - net-magento

  db:
    image: mysql:8.0.41
    container_name: magento_db
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - net-magento

  # redis:
  #   image: redis:6.0.20
  #   container_name: magento_redis
  #   ports:
  #     - "6380:6381"
  #   networks:
  #     - net-magento

  # elasticsearch:
  #   image: elasticsearch:7.16.1
  #   container_name: magento_elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - ES_JAVA_OPTS=-Xms1g -Xmx1g
  #   ports:
  #     - "9201:9200"
  #   networks:
  #     - net-magento

networks:
  net-magento:

volumes:
  db_data:
