services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: