services:
  mage247_php:
    image: php:8.3.19-fpm
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: mage247_php
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    ports:
      - "9001:9000"
    networks:
      - magento247_nets

  mage247_nginx:
    image: nginx:1.18
    container_name: mage247_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx:rwx
    depends_on:
      - mage247_php
    networks:
      - magento247_nets

  mage247_mysql:
    image: mysql:8.0.41
    container_name: mage247_db
    restart: no
    command: --sql-mode=''
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento123
      MYSQL_DATABASE: magento
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-dump/magento.sql:/docker-entrypoint-initdb.d/magento.sql
      - ./db_data:/var/lib/mysql:rw
    user: mysql
    depends_on:
      - mage247_nginx
    networks:
      - magento247_nets

  mage247_redis:
    image: redis:7.2
    container_name: mage247_redis
    ports:
      - "6380:6381"
    networks:
      - magento247_nets

  mage247_els:
    image: elasticsearch:8.16.6
    container_name: mage247_els
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9201:9200"
    networks:
      - magento247_nets
  mage247_phpmyadmin:
    image: phpmyadmin:5.2-fpm
    container_name: mage247_phpmyadmin
    restart: none
    environment:
      - PMA_HOST=mage247_db
      - PHP_MEMORY_LIMIT=1024M
    ports:
      - 81:80
    networks:
      - magento247_nets

networks:
  magento247_nets:
