services:
    postgres174:
        image: postgres
        shm_size: 1280mb
        user: postgres
        ports:
            - 5432:5432
        restart: none
        deploy:
            mode: replicated
            replicas: 1
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin123
        volumes:
            - pgdata:/var/lib/postgresql/data

    # adminer:
    #     image: adminer
    #     restart: none
    #     ports:
    #         - 8080:8080
volumes:
    pgdata:

# docker run --name postgres174 -e POSTGRES_PASSWORD=admin123 -d postgres:17.4
